### ISSUE TITLE
Glitch Not working anymore

### ISSUE THREAD

**Issue by henfri** [foscoj/lohnt-sich-awattar#14]
Hello, 

Unfortunately, the Glitch Site does Not Work anymore.
Could you restore it, please?regards,
Hendrik

**Comment by foscoj** [comment]
Sorry, glitch changed something, simple restore is not possible.
You would have to try the script locally or maybe the hints for online jupyter notebooks in https://github.com/foscoj/Battery-Simulation may help. You could just copy this code in the py file to a new jupyter online Notebook and try to run it there.

The battery simulation would be a better base for this project anyway, I just have no motivation to port it, as awattar and tibber are currently not a viable option for my use case any more.

**Comment by henfri** [comment]
understood, thanks!
